limits:
  daily: 30
messages:
  send: 2
threads:
  send: 2
  receive: 1
reactions:
  atena: 0.1
  send: 1
  receive:
    positive: 2
    negative: -1
github:
  issue: 1
  review: 1
  pull_request: 1
  merged_pull_request: 3
disqus:
  comment: 2
inactive:
  mindays: 8
  value: -2
linkedin: 3
team:
  interview: 5
  approved: 7
  allocated: 9
referral: 3
